{
    "name": "Sdoo China Country Pack",
    "summary": "Governed China fiscal compliance profiles and country-pack foundations",
    "version": "19.0.1.60.0",
    "category": "Accounting/Accounting",
    "author": "Sdoo",
    "license": "LGPL-3",
    "depends": [
        "sudo_global_finance",
        "account",
        "l10n_cn",
    ],
    "data": [
        "security/compliance_security.xml",
        "security/ir.model.access.csv",
        "data/compliance_report_sequence.xml",
        "data/country_pack_data.xml",
        "data/official_source_candidates.xml",
        "data/compliance_fact_data.xml",
        "data/compliance_rule_drafts.xml",
        "data/rule_review_candidates.xml",
        "data/invoice_reconciliation_cron.xml",
        "data/vat_period_reconciliation_cron.xml",
        "data/cit_period_reconciliation_cron.xml",
        "data/iit_period_reconciliation_cron.xml",
        "data/source_monitoring_cron.xml",
        "reports/rule_review_packet_report.xml",
        "reports/vat_adjustment_report.xml",
        "reports/compliance_report.xml",
        "views/rule_review_packet_views.xml",
        "views/rule_governance_views.xml",
        "views/workbench_views.xml",
        "views/risk_center_views.xml",
        "views/compliance_integration_views.xml",
        "views/data_readiness_center_views.xml",
        "views/invoice_normalization_views.xml",
        "views/invoice_reconciliation_views.xml",
        "views/tax_data_normalization_views.xml",
        "views/cit_filing_views.xml",
        "views/iit_withholding_views.xml",
        "views/payroll_summary_views.xml",
        "views/iit_accounting_scope_views.xml",
        "views/iit_period_reconciliation_views.xml",
        "views/cit_accounting_scope_views.xml",
        "views/cit_period_reconciliation_views.xml",
        "views/vat_accounting_scope_views.xml",
        "views/vat_period_reconciliation_views.xml",
        "views/filing_archive_views.xml",
        "views/tax_impact_review_views.xml",
        "views/compliance_report_views.xml",
        "views/report_readiness_views.xml",
        "views/ai_guidance_views.xml",
        "views/evidence_center_views.xml",
        "views/filing_center_views.xml",
        "views/source_monitoring_views.xml",
        "views/jurisdiction_views.xml",
        "views/cross_border_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
